# Generated by Django 4.1.7 on 2023-05-18 19:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='F.I.SH')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Telefon raqamingiz 9 bilan boshlanishi va 12 ta belgidan oshmasligi lozim. Masalan: 998993451545', regex='^998[0-9]{9}$')], verbose_name='Telefon nomer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish vaqti')),
                ('sponsor_type', models.CharField(choices=[('PHYSICAL_PERSON', 'Jismoniy shaxs'), ('LEGAL_ENTITY', 'Yuridik shaxs')], default='PHYSICAL_PERSON', max_length=31, verbose_name='Homiy turi')),
                ('organization_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Tashkilot nomi')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('IN_MODERNIZATION', 'Modernizatsiyada'), ('APPROVED', 'Tasdiqlangan'), ('CANCELLED', 'Bekor qilingan')], default='NEW', max_length=31, verbose_name='Holati')),
                ('payment_type', models.CharField(blank=True, choices=[('VIA_CASH', 'Naqd pul'), ('VIA_CARD', 'Plastik karta'), ('VIA_BANK', 'Bank hisobi')], max_length=32, null=True, verbose_name="To'lov turi")),
                ('payment_amount', models.PositiveIntegerField(verbose_name='Homiylik summasi')),
                ('amount_spent', models.PositiveIntegerField(default=0, verbose_name='Sarflangan summa')),
            ],
            options={
                'verbose_name_plural': 'Homiylar',
                'ordering': ('created_at',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64, verbose_name='F.I.SH')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Telefon raqamingiz 9 bilan boshlanishi va 12 ta belgidan oshmasligi lozim. Masalan: 998993451545', regex='^998[0-9]{9}$')], verbose_name='Telefon nomer')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilanish vaqti')),
                ('university_name', models.CharField(max_length=64, verbose_name='Unversitet nomi')),
                ('degree_type', models.CharField(choices=[('BACHELOR', 'Bakalavr'), ('MASTER', 'Magistr')], max_length=15, verbose_name='Talabalik turi')),
                ('payment_amount', models.PositiveIntegerField(verbose_name='Kontrakt miqdori')),
                ('amount_spent', models.PositiveIntegerField(default=0, verbose_name='Ajratilgan summa')),
            ],
            options={
                'verbose_name_plural': 'Talabalar',
                'ordering': ('created_at',),
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Metsenat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
            options={
                'verbose_name_plural': 'Metsenat',
                'ordering': ('-created_at',),
            },
        ),
    ]
