# Generated by Django 4.1.7 on 2023-05-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='full_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='F.I.SH'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='F.I.SH'),
        ),
    ]
