# Generated by Django 4.1.7 on 2023-05-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0002_alter_telegramid_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramid',
            name='telegram_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
